### ISSUE TITLE
Fix Event bug for startDateTime

### ISSUE THREAD

**Issue by szenius** [cs2103aug2015-f10-2j/main#121]
When you add an event, update its name, then do an undo, this pops out:

Exception in thread "main" java.lang.NullPointerException
    at java.util.Calendar.setTime(Calendar.java:1770)
    at java.text.SimpleDateFormat.format(SimpleDateFormat.java:943)
    at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936)
    at java.text.DateFormat.format(DateFormat.java:345)
    at Tempo.Event.getStartDate(Event.java:105)
    at Tempo.Event.toString(Event.java:164)
    at Tempo.CalendarExporter.export(CalendarExporter.java:36)
    at Tempo.Calendar.exportToFile(Calendar.java:541)
    at Tempo.Calendar.undo(Calendar.java:335)
    at Tempo.UndoCommand.execute(UndoCommand.java:13)
    at Tempo.tempRequestHandler.processCommand(tempRequestHandler.java:25)
    at Tempo.Tempo.listenForInput(Tempo.java:94)
    at Tempo.Tempo.run(Tempo.java:46)
    at Tempo.Tempo.main(Tempo.java:35)

Not sure what's the problem with getStartDate(), the problem seems to be occuring when exporting to file!!

**Comment by ngzikai** [comment]
Fixed with #130
